name: Deploy FastAPI App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "Dockerfile,requirements.txt,main.py,services,routers,docker-compose.yml,frontend"
        target: "~/tnc_app"
        timeout: 60s
        command_timeout: 15m

    - name: Deploy Docker containers on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/tnc_app
          export GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
          export GROQ_MODEL=${{ secrets.GROQ_MODEL }}
          export CHUNK_SIZE=${{ secrets.CHUNK_SIZE }}
          export CHUNK_OVERLAP=${{ secrets.CHUNK_OVERLAP }}
          export EMBEDDING_MODEL=${{ secrets.EMBEDDING_MODEL }}
          export PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}
          export GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          docker compose down
          docker compose up -d --build
